# pyQchem Tutorial Part II

## Outputfile processing

In [54]:
import pyqchem as qc

Now we read in an output file:

In [55]:
ls

a.out                  h2_batch.inp           pocop_batch.out        testrun2.out           tutorial_output.html
aimd.out               iqmol.png              pocop_co.out           trajectory.xyz         tutorial_output.ipynb
b.out                  mm_opt.out             pocop_eth.out          tutorial_input.html
ethane.inp             oniom_opt.out          testrun.out            tutorial_input.ipynb


In [56]:
out = qc.read("pocop_co.out")

Outputfile detected.
Unsupported array type opt detected. Read as constant.


pyQChem is pretty talkative. It will tell you what it is doing while loading a file. This is not always desired, e.g. in scripts when it is called numerous times. To make it shut up, use the silent mode:

In [57]:
out = qc.read("pocop_co.out", silent=1)

Tab completion shows us what is available for this object we created:

In [58]:
out.general

We have two info objects available, **general** and **opt**.
The first object, **general** is part of EVERY outputfile.
It contains basic information about the job. Every info object knows a method named *info*, which gives us an overview:

In [59]:
out.general.info()

About this job:
--------------

Q-Chem version:		4.0.1
Jobtype:		opt
Basis functions:	789
Spin:			0.0
SCF energy:		-3145.8818915
Status:			finished


Now, at least everything that is listed in these *info* blocks (usually more than that) is also available as a variable. Again, use tab completion to see what is there:

In [60]:
out.general.version

'4.0.1'

In [61]:
out.general.energy

-3145.8818914969

The **general** object also holds the corresponding input file for convenience, derived from the output:

In [62]:
out.general.inputfile

We can grab it and treat it as we did in tutorial I on input files:

In [63]:
myinp = out.general.inputfile
myinp.rem.scf_convergence()

'8'

In [64]:
myinp.rem.scf_convergence("10")

In [65]:
print(myinp.rem)

$rem
SYMMETRY                      false
BASIS                         gen
GEOM_OPT_TOL_ENERGY           40
GEOM_OPT_MAX_CYCLES           500
THRESH                        14
MEM_TOTAL                     16000
MOLDEN_FORMAT                 true
JOBTYPE                       opt
THRESH_RCA_SWITCH             7
SCF_ALGORITHM                 rca_diis
GEOM_OPT_TOL_GRADIENT         300
GEOM_OPT_TOL_DISPLACEMENT     40
ECP                           gen
SCF_CONVERGENCE               10
MAX_SCF_CYCLES                500
EXCHANGE                      b3lyp
MAX_RCA_CYCLES                10
INCDFT                        0
SYM_IGNORE                    true
MEM_STATIC                    4000
XC_GRID                       000075000302
INCFOCK                       0
UNRESTRICTED                  true
SCF_GUESS                     sad
$end



### Optimization output

Since this outputfile is of type 'opt' also contains an optional info object named **opt**:

In [66]:
out.opt

Again, we call the *info* method first, and find that it contains a summary of the optimization:

In [67]:
out.opt.info()

Summary of geometry optimization:
--------------------------------

Energy		Gradient	Displacement	DeltaE
-3145.826978357	0.000000000	0.225946000	0.000000000	
-3145.869808193	0.259299000	0.062678000	-0.042830000	
-3145.873236246	0.097171000	0.017411000	-0.003428000	
-3145.874398274	0.040532000	0.025235000	-0.001162000	
-3145.875046836	0.014582000	0.038872000	-0.000649000	
-3145.875740269	0.016368000	0.050176000	-0.000693000	
-3145.876350127	0.019899000	0.023494000	-0.000610000	
-3145.876593444	0.009878000	0.022841000	-0.000243000	
-3145.876868412	0.006035000	0.023662000	-0.000275000	
-3145.877089609	0.007039000	0.020366000	-0.000221000	
-3145.877252070	0.009444000	0.015182000	-0.000162000	
-3145.877378978	0.006411000	0.011026000	-0.000127000	
-3145.877498530	0.002496000	0.011736000	-0.000120000	
-3145.877624833	0.005415000	0.014077000	-0.000126000	
-3145.877758644	0.006429000	0.016361000	-0.000134000	
-3145.877903725	0.004237000	0.021272000	-0.000145000	
-3145.878083103	0.003005000	0.02

What else is there? A status variable:

In [68]:
out.opt.status

'converged'

And the geometries...

In [69]:
print(out.opt.geometries[-1])  # grabbing the last one

84
Optimization step 195
H    7.027601    -3.396162    0.602089
H    8.650101    1.014758    -2.711851
H    8.981031    0.613238    -0.291041
H    7.215761    -1.550422    2.243309
O    5.373715    -1.453681    0.304992
O    6.666133    0.139770    -1.614921
Si    8.348937    0.149846    -1.592464
Si    6.296084    -2.371581    1.366049
H    5.341431    1.902978    3.036579
H    6.572221    3.411518    1.269589
H    8.834261    -1.181862    -1.991421
H    5.290961    -3.101742    2.111299
H    3.734411    3.287678    1.143269
O    5.182498    1.359338    0.485950
Si    5.188477    2.628050    1.590808
Ti    5.148441    0.018788    -0.680642
O    3.631895    -0.010462    -1.698338
C    1.662269    1.207261    -1.099161
C    2.324929    -0.014949    -1.293555
C    1.682834    -1.239844    -1.057084
C    0.368607    -1.210381    -0.588741
C    -0.340585    -0.020043    -0.349185
C    0.349715    1.173013    -0.626839
O    -0.288606    2.383902    -0.408549
P    -1.861652    2.258007    0.

### Frequencies output

We start with loading a freq job:

In [70]:
ls

a.out                  h2_batch.inp           pocop_batch.out        testrun2.out           tutorial_output.html
aimd.out               iqmol.png              pocop_co.out           trajectory.xyz         tutorial_output.ipynb
b.out                  mm_opt.out             pocop_eth.out          tutorial_input.html
ethane.inp             oniom_opt.out          testrun.out            tutorial_input.ipynb


In [71]:
myfreq = qc.read("pocop_eth.out")

Outputfile detected.
Unsupported array type isotopes detected. Read as constant.


In [72]:
myfreq.general.info()

About this job:
--------------

Q-Chem version:		4.0.1
Jobtype:		freq
Basis functions:	637
Spin:			0.0
SCF energy:		-1878.46858176
Status:			finished


Let us have a look at the second info object, once again, using the *info()* method: 

In [73]:
myfreq.thermo.info()

Electronic energy (E):		-1878.46858176
---------------------

Corrections to E:
-----------------
Zero point energy (ZPE):	[ 0.62098186  0.62098186  0.62098186]
Internal thermal energy (ITE):	[ 0.65779883  0.68365183  0.70676702]

Temperature (T in Kelvin):	[ 298.18  398.15  473.15]
-------------------------

Pressure (p in Pa):		[ 101325.  101325.  101325.]
------------------

Thermodynamic potentials:
------------------------
Entropy (S):			[ 0.00034538  0.00042065  0.00047429]
Enthalpy (H):			[-1877.80983792 -1877.78366939 -1877.76031676]
Helmholtz free energy (F):	[-1877.91376966 -1877.95241245 -1877.98622546]
Gibbs free energy (G):		[-1877.91282465 -1877.95115191 -1877.98472747]


It contains a summary of the thermodynamics calculation. If we are unsure about the output we can get help with the question mark operator.

In [74]:
myfreq.thermo.info?

Note that all qualities come in triples, this means that the freq job had 3 loops. Let's have a look at the inputfile:

In [75]:
print(myfreq.general.inputfile)

$rem
SYMMETRY                      false
BASIS                         gen
THRESH                        14
MEM_TOTAL                     16000
MOLDEN_FORMAT                 true
JOBTYPE                       freq
THRESH_RCA_SWITCH             7
SCF_ALGORITHM                 rca_diis
NBO                           true
SCF_CONVERGENCE               9
ECP                           gen
MAX_SCF_CYCLES                500
EXCHANGE                      b3lyp
MAX_RCA_CYCLES                10
INCDFT                        0
INCFOCK                       0
ISOTOPES                      true
MEM_STATIC                    4000
XC_GRID                       000075000302
SYM_IGNORE                    true
UNRESTRICTED                  true
SCF_GUESS                     sad
$end

$comment
Gibbs energies at 20, 125 and 200 deg C
$end

$basis
H
cc-pVDZ
****
C
cc-pVDZ
****
Ir
LANL2DZ
****
O
cc-pVDZ
****
P
cc-pVDZ
****
$end

$ecp
Ir
LANL2DZ
****
$end

$molecule
0 1
C    -1.970942    0.769824    0.001784


What else is in the **thermo** object of our outputfile? All thermodynamic variables and potentials are directly accessible: 

In [76]:
myfreq.thermo.G

array([-1877.91282465, -1877.95115191, -1877.98472747])

In [77]:
myfreq.thermo.mass

array([ 618.23733,  618.23733,  618.23733])

In [78]:
myfreq.thermo.S

array([ 0.00034538,  0.00042065,  0.00047429])

Note: pyQchem comes with a library of useful constants and conversion factors. They are sitting in the object **constants**. Use tab completion to find what you need:

In [79]:
myfreq.thermo.S*qc.constants.hartree_to_kcal_pro_mole

array([ 0.216732,  0.263963,  0.297622])

The **thermo** object also knows a powerful method named calculate(), which allows for an 'a posteriori' thermodynamics caclulation based on the frequencies given in the outputfile. Let's get some help first:

In [80]:
myfreq.thermo.calculate?

And then, use it to calculate G for a temperatures between 100 and 500 C at 2 bar:

In [81]:
results = myfreq.thermo.calculate([373,473,573,673,773],2e5)

Results based on frequencies of loop 0 and isotopes of loop 0
-------------------------------------------------------------

T	p		ITE		 S		 H		 F		 G
373.00	200000.00	0.6765901	0.0004000	-1877.7908105	-1877.9411842	-1877.9400030	
473.00	200000.00	0.7067183	0.0004720	-1877.7603655	-1877.9851373	-1877.9836394	
573.00	200000.00	0.7418014	0.0005398	-1877.7249657	-1878.0360815	-1878.0342670	
673.00	200000.00	0.7810015	0.0006033	-1877.6854490	-1878.0935866	-1878.0914553	
773.00	200000.00	0.8236392	0.0006627	-1877.6424947	-1878.1572362	-1878.1547882	


The same structure as printed is also returned by the function. Here I print the Gibbs free energy, which is the last column of the returned array:

In [82]:
results[:, 6]

array([-1877.94000297, -1877.98363937, -1878.03426696, -1878.09145534,
       -1878.1547882 ])

### Batch outputfiles

Batch outputfiles can be read in as usual. We create an batch output object named *multi*:

In [83]:
multi = qc.read("pocop_batch.out")

Batch-Outputfile detected.
Unsupported array type isotopes detected. Read as constant.


The structure is similar to batch inputfiles. Again, we have two lists accesible:

In [84]:
multi.list_of_content

['opt', 'freq']

In [85]:
multi.list_of_jobs

As an example, we take a closer look at the first job, an optimization:

In [86]:
first = multi.list_of_jobs[0]

The object *first* is now an outputfile object an can be treated as shown above:

In [87]:
first.opt.info()

Summary of geometry optimization:
--------------------------------

Energy		Gradient	Displacement	DeltaE
-1799.831259853	0.000000000	0.092735000	0.000000000	
-1799.836548741	0.015842000	0.077467000	-0.005289000	
-1799.836728062	0.004263000	0.125397000	-0.000179000	
-1799.836521339	0.002506000	0.082155000	0.000207000	
-1799.836810112	0.004456000	0.014902000	-0.000289000	
-1799.836815717	0.000314000	0.023231000	-0.000006000	
-1799.836812741	0.000256000	0.017563000	0.000003000	
-1799.836817722	0.000988000	0.011472000	-0.000005000	
-1799.836816371	0.000102000	0.008050000	0.000001000	
-1799.836817992	0.000276000	0.001436000	-0.000002000	
-1799.836818014	0.000032000	0.000409000	0.000000000	


### QM/MM calculations

We start with a MM only job: 

In [88]:
mm_out = qc.read("mm_opt.out")

Outputfile detected.
Unsupported array type force_field_params detected. Read as constant.


This job has only MM energy, no spin, no basis information.

In [89]:
mm_out.general.info()

About this job:
--------------

Q-Chem version:		4.0.1
Jobtype:		opt (MM calculation)
MM energy:		-0.005006501207
Status:			finished


Yet, it is an optimization and therefore has a opt info object. Note that the energy stems from an MM calculation, but is given in Hartree for consistency.

In [90]:
mm_out.opt.info()

Summary of geometry optimization:
--------------------------------

Energy		Gradient	Displacement	DeltaE
0.053936023	0.000000000	0.121156000	0.053936000	
0.031030805	0.067498000	0.146685000	-0.022905000	
0.020795524	0.043128000	0.080008000	-0.010235000	
0.019992655	0.012418000	0.148323000	-0.000803000	
0.019474491	0.002538000	0.230845000	-0.000518000	
0.027860160	0.004835000	0.219788000	0.008386000	
0.017982894	0.039331000	0.279201000	-0.009877000	
0.014729452	0.008990000	0.260137000	-0.003253000	
0.011625358	0.010976000	0.257009000	-0.003104000	
0.008301859	0.014913000	0.199202000	-0.003323000	
0.004836007	0.020256000	0.267878000	-0.003466000	
0.001839830	0.021710000	0.262378000	-0.002996000	
-0.001760469	0.025228000	0.221817000	-0.003600000	
-0.003483545	0.021454000	0.156308000	-0.001723000	
-0.003913722	0.015975000	0.091898000	-0.000430000	
-0.004979620	0.013285000	0.038523000	-0.001066000	
-0.005000095	0.001090000	0.008171000	-0.000020000	
-0.005006316	0.000732000	0.001766000	-0.00

Whenever a job contains an MM calculation, pyQChem will also create info objects containing the FF energy contributions.

In [91]:
mm_out.mm.info()

MM calculation summary
----------------------

19 energies found, printing last:

Number of bonds:		9
Bond energy:			0.003380401612 kcal/mol
Angle energy:			0.003278483484 kcal/mol
Urey-Bradly energy:		0.008419976061 kcal/mol
Improper rotation energy:	0.0 kcal/mol
Torsion energy:			0.033042062086 kcal/mol
van der Waals energy:		0.179707355114 kcal/mol
Coulomb energy:			-3.36945520252 kcal/mol
-------------------------
Total energy:			-3.14162692416 kcal/mol (-0.00500650118196 Hartree)


Now, what happens if we read a QM/MM outputfile?

In [92]:
oniom = qc.read("oniom_opt.out")

Outputfile detected.
Unsupported array type qm_atoms detected. Read as constant.


In [93]:
oniom.general.info()

About this job:
--------------

Q-Chem version:		4.0.1
Jobtype:		opt (QM/MM calculation of type ONIOM)
Basis functions:	19
Spin:			0.0
QM/MM total energy:	-69.9172784837
Status:			unfinished


In the case of a Janus job we find ONE extra info object named **mm** describing the MM part.
For ONIOM calculations (example given) there are two objects present, one for the total system, one for the model subset:

In [94]:
oniom.mm_total, oniom.mm_model

(<pyQChem.output_classes._mm at 0x10760a5d0>,
 <pyQChem.output_classes._mm at 0x10760a490>)

In [95]:
oniom.mm_model.info()

MM calculation summary
----------------------

50 energies found, printing last:

Number of bonds:		2
Bond energy:			5.04671782843 kcal/mol
Angle energy:			0.017366650812 kcal/mol
Urey-Bradly energy:		0.531139409663 kcal/mol
Improper rotation energy:	0.0 kcal/mol
Torsion energy:			0.0 kcal/mol
van der Waals energy:		0.0 kcal/mol
Coulomb energy:			0.0 kcal/mol
-------------------------
Total energy:			5.5952238889 kcal/mol (0.00891655683164 Hartree)


Let's have a look at the last MM energies in the file, and the total energy after QM addition:

In [96]:
E_mm_total = oniom.mm_total.etot[-1]*qc.constants.kcal_pro_mole_to_hartree
E_mm_model = oniom.mm_model.etot[-1]*qc.constants.kcal_pro_mole_to_hartree
E_qmmm = oniom.opt.energies[-1]

In [97]:
(E_mm_total, E_mm_model, E_qmmm)

(0.001197310569047315, 0.00891655683163947, -69.917278484)

According to the ONIOM definition the pure QM energy could be obtained here via

In [98]:
E_qmmm - E_mm_total + E_mm_model

-69.90955923773741

### AIMD output files

The following batch outputfile contains two calculations:

In [99]:
md_job = qc.read("aimd.out")

Batch-Outputfile detected.


In [100]:
md_job.list_of_content

['freq', 'aimd']

Let's have a look at the AIMD part:

In [101]:
job1 = md_job.list_of_jobs[1]

Surprise surprise, this job contains an info array named **aimd**! We call its info method to get the details:

In [102]:
job1.aimd.info()

Summary of AIMD calculation:
--------------------------------

Step	energies	time (fs)	drift
1	-154.930261198	    0.00	-0.05000	
2	-154.918118615	   20.00	-0.18000	
3	-154.902340307	   40.00	-0.35000	
4	-154.886893702	   60.00	-0.51700	
5	-154.874985826	   80.00	-0.64600	
6	-154.868447005	  100.00	-0.71700	
7	-154.867616522	  120.00	-0.72700	
8	-154.871685646	  140.00	-0.68400	
9	-154.879118566	  160.00	-0.60400	
10	-154.887851069	  180.00	-0.51000	
11	-154.895331403	  200.00	-0.43000	
12	-154.898726721	  220.00	-0.39500	
13	-154.895662725	  240.00	-0.42900	
14	-154.885670330	  260.00	-0.53700	
15	-154.871829300	  280.00	-0.68400	
16	-154.860868780	  300.00	-0.79900	
17	-154.859753253	  320.00	-0.81000	
18	-154.870203276	  340.00	-0.70000	
19	-154.886866778	  360.00	-0.52300	
20	-154.901573398	  380.00	-0.36600	
21	-154.908710888	  400.00	-0.28900	
22	-154.907080467	  420.00	-0.30400	
23	-154.898788817	  440.00	-0.39200	
24	-154.887468574	  460.00	-0.51300	
25	-154.876848698	  480.00	-

This job consists of 200 steps. The size of each timestep is 20 fs. Beside energies, time steps and energy drift this info object also contains the kinetic energies, the geometries, and relevant parameters such as temperature.

In [103]:
job1.aimd.geometries[0:5]

For a quick and easy visualisation of the trajectory the **aimd** info object also knows a method named *write_trajectory_xyz("my_filename")*, which concatenates all geometries to a series of xyz-coordinates and saves them into a textfile "my_filename", using the corresponding energy as title. This format is e.g. supported by Molden, which allows a visualistion of the geometries and the energies at the same time. If no filename is specified, a file "trajectory.xyz" will be created.

In [104]:
job1.aimd.write_trajectory_xyz()

In [105]:
ls

a.out                  h2_batch.inp           pocop_batch.out        testrun2.out           tutorial_output.html
aimd.out               iqmol.png              pocop_co.out           trajectory.xyz         tutorial_output.ipynb
b.out                  mm_opt.out             pocop_eth.out          tutorial_input.html
ethane.inp             oniom_opt.out          testrun.out            tutorial_input.ipynb
